<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgyDYb2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgyDYb2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQgyDYb2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQgyDYb2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQgyDYb2\App_KernelDevDebugContainer([
    'container.build_hash' => 'QgyDYb2',
    'container.build_id' => '73820430',
    'container.build_time' => 1678882333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgyDYb2');
