<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0CouXTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0CouXTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0CouXTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0CouXTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0CouXTx\App_KernelDevDebugContainer([
    'container.build_hash' => '0CouXTx',
    'container.build_id' => '19e7e5c7',
    'container.build_time' => 1679047081,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0CouXTx');
