vich_uploader:
    metadata:
        type: attribute

    db_driver: orm

    mappings:
        post:
            uri_prefix: '%post_image%'
            upload_destination: '%kernel.project_dir%/public%post_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
