<?php

namespace ContainerY8tT6QA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_829rDxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.829r_dx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.829r_dx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'levelRepository' => ['privates', 'App\\Repository\\LevelRepository', 'getLevelRepositoryService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'levelRepository' => 'App\\Repository\\LevelRepository',
            'postRepository' => 'App\\Repository\\PostRepository',
        ]);
    }
}
